services:
  - type: web
    name: utme-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: PREMIUM_PRICE
        value: 2000
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://utmebot.onrender.com
