services:
  - type: web
    name: utme-success-bot-v17-4
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
        value: YourBot
      - key: ALOC_ACCESS_TOKEN
        sync: false
      - key: PAYMENT_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PREMIUM_PRICE
        sync: false
        value: 2000
      - key: FREE_MOCK_QS_DAILY
        sync: false
        value: 5
      - key: FREE_TUTOR_PER_DAY
        sync: false
        value: 2
      - key: REFERRAL_REQUIRED
        sync: false
        value: 3
      - key: REFERRAL_REWARD_DAYS
        sync: false
        value: 7
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_SECRET_HASH
        sync: false
        value: utme_webhook_hash_123
      - key: FLW_ENCRYPTION_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
        value: UTMESUCCESS
      - key: PAYSTACK_SECRET_KEY
        sync: false
